MonashUnitPlanner/monPlanR

app/components/CourseStructure.jsx, app/components/InsertTeachingPeriod.jsx, app/components/TeachingPeriod.jsx, app/components/Unit.jsx, app/index.html
Adding teaching periods is a WIP
=> [UI] improvements to course structure and moved some components around

README.md, app/components/CourseStructure.jsx, app/components/Unit/UnitInfoPlaceholder.jsx, app/components/base/Header.jsx, app/components/base/Home.jsx, app/components/modals/ControlledModal.jsx, app/components/modals/privacy.jsx, app/components/modals/tos.jsx, app/data/teachingPeriods/all.json, app/data/teachingPeriods/common.json, package.json
Inspired from [study.monash](http://study.monash), table header "Units" in CourseStructure now only appears once, with colSpan set to the number of unit slots available (default=4).
=> [UI] better CourseStructure table header layout

app/components/CourseStructure.jsx, app/components/TeachingPeriod/TeachingPeriod.jsx, app/components/Unit/SetuRating.jsx, app/components/Unit/UnitInfo.jsx, app/components/base/Header.jsx, app/components/base/Home.jsx, app/components/base/Plan.jsx, app/index.html, package.json
Another dependency has been added, called `react-responsive`. This just helps with handling CSS media queries.
So run `npm install` after pulling these changes.
=> [UI] Slight tweaks to make site a little more responsive

app/components/base/Home.jsx, app/containers/YearFormContainer.jsx, app/utils/YearCalc.js
No longer uses plain text input, no use trusting users because it takes too much time to validate dynamically. Still has some work that could be done but completely functional right now. Uses a dropdown where the end year selection is updated dynamically based on start year
=> Updating year select form to be waaaaaay faster

app/components/CollapseButton.jsx, app/components/Unit/UnitInfo.jsx
Now shows unit name of the detail view it is presenting
=> Unit detail collapse button update

app/components/base/Home.jsx, app/containers/YearFormContainer.jsx
Home page emphasises that users have two options, and it handles both mobile and desktop modes.
TODO: Find some better way to illustrate that these buttons are two separate options, with each one explaining clearly what they do.
=> [UI] Slight tweaks to home page

app/containers/UnitInfoContainer.jsx, app/containers/UnitSearchContainer.jsx
This commit improves the usability of the web app. Discussed with jos0003.
=> Automatically selects first result, removed green button

app/components/Unit/Unit.jsx, app/components/Unit/UnitInfo.jsx, app/components/base/Header.jsx, app/containers/UnitInfoContainer.jsx
- replacing menu icon
- updating version
- issue fixes
- feedback button
=> [UI] Minor changes prepping for v0.1.0 release 

app/components/Unit/UnitInfo.jsx, app/containers/UnitDescriptionContainer.jsx, app/containers/UnitInfoContainer.jsx
* Shows the credit point value for a unit
* Shows the estimated cost of a unit
* Also added show more/less implementation for unit descriptions over 300 chars
=> [CRE] - Added unit cost and unit credit point calculation

app/components/CourseStructure.jsx, app/components/Unit/UnitInfo.jsx, app/components/base/Plan.jsx, app/containers/OfferingContainer.jsx, app/containers/UnitInfoContainer.jsx, app/utils/CostCalc.js, app/utils/UnitQuery.js
+ added individual credit point info to unit detail view
+ added individual cost info to unit detail view
+ added location info to unit detail view
+ added cost and credit point totals to main page
+ various documentation and linting fixes
=> [CRE] Added unit credit point and cost totals, added location info.

app/components/CourseStructure.jsx, app/components/TeachingPeriod/TeachingPeriod.jsx, app/components/modals/ConfirmDeleteTeachingPeriod.jsx
+ Confirm delete modal now appears for teaching periods containing units
- Also removed unnecessary extended.json file now that we have API
=> Adde confirm remove modal for teaching periods

app/components/CourseStructure.jsx, app/components/modals/ConfirmDeleteOverload.jsx, app/components/modals/ConfirmDeleteTeachingPeriod.jsx, app/utils/CostCalc.js
=> [UI] - Added confirmation of removal of overload columns with units in them

app/components/CourseStructure.jsx
=> [FIX] - Credit point and cost totals now update correctly when removing columns or rows

app/components/multi/test.jsx, app/utils/fuzzy.js
- fuzzy search now has a test environment at /test
=> [CRE] fixed up test harness for fuzzy search, available at /test

app/utils/fuzzy.js, package.json
SAURABH USE THIS FOR INTERGRATION OTHERWISE READ IT RIGHT NOW
=> PR: Fuse.js update settings as well as changing package.json

app/components/CourseStructure.jsx, app/utils/UnitQuery.js
- currently in the form of a button on main page,
- only works for one course as the query is hardcoded,
- will need to wait on API upgrade to flesh out fully
=> Added test harness for loading a course template from API

app/components/CourseStructure.jsx, app/components/modals/ClearCourseModal.jsx, app/components/modals/ConfirmDeleteOverload.jsx, app/components/modals/ConfirmDeleteTeachingPeriod.jsx, app/utils/CourseTemplate.js, app/utils/UnitQuery.js
+ updated delete confirmation modals to be standardised
+ linted and commented touched files
+ made CourseTemplate algorithm more robust so it can handle courses with overloading correctly
=> [UI] [DEV] [CRE] - Documentation, linting, modals update and overload course import

app/components/base/Home.jsx
this _PR_ adds a **warning message** to the user to show that they will need to clear course because of the version they are running on their browser
=> added error message

app/components/CourseStructure.jsx, app/components/base/404.jsx, app/components/base/Footer.jsx, app/components/base/Header.jsx, app/components/modals/ConfirmDeleteOverload.jsx, app/components/modals/ConfirmDeleteTeachingPeriod.jsx, app/containers/OfferingContainer.jsx, app/index.html, app/resources/css/custom.css
+ fixed routing issue where extended 404 paths would cause css links to break
+ updated feedback link for new form
+ fixed key assignment errors to do with multiple units having same unitcode (ex: "free electives")
+ fixed bug where units with a teaching period of "Not offered" were not rendering at all
=> [UI][FIX] - FIxing backlog of minor UI changes and bug fixes pre-release

app/components/CourseStructure.jsx, app/components/TeachingPeriod/TeachingPeriod.jsx, app/components/Unit/Unit.jsx, app/components/base/Header.jsx, app/components/base/Main.jsx, app/components/base/Plan.jsx
All it does right now is it checks for duplicate units, and highlights one of them accordingly
The status menu item at the header does not update straight away, due to the structure of the components, and the principles of React (one way data binding). Lifting state up might make the app too complicated, so we need to consider using Redux for managing the state.
=> [CRE] [UI] First implementation of validating course plan

app/actions/draft.json, app/components/Course/CourseStructure.jsx, app/components/modals/LoadCourseMap.jsx, package.json
- fixed load course map enabling too early
- display API status more clearly
- started drafting redux (by creating an app/actions/draft.json file to brainstorm many of the actions that will be implemented by using reducers)
Please run `npm install` after you pull these changes.
=> Cumulative update

app/components/base/Home.jsx, app/components/base/Main.jsx, app/reducers/Counter.js, app/tests/CounterTestSuite.js, app/tests/FullTestSuite.js, package.json
Added a test example for a reducer and started building up architecure for automated testing
=> [CRE] [DEV] Test framework architecture - REQUIRES NPM INSTALL

app/components/base/Home.jsx, app/components/base/Plan.jsx, app/config/routes.js, app/containers/CourseSelectFormContainer.jsx, app/containers/YearFormContainer.jsx, app/resources/css/custom.css
Entry form not completed in terms of routing, but based Eric demands access ;)
=> [CRE] For Eric <3

.eslintrc, app/components/Course/CourseDescription.jsx, app/components/Course/CourseDetailPopup.jsx, app/components/Course/CourseInfo.jsx, app/components/Course/CourseStructure.jsx, app/components/TeachingPeriod/NoTeachingPeriod.jsx, app/components/Unit/Unit.jsx, app/components/Unit/UnitDetailModal.jsx, app/components/Unit/UnitDragPreview.jsx, app/components/Unit/UnitInfo.jsx, app/components/base/Main.jsx, app/components/base/Plan.jsx, app/components/base/View.jsx, app/containers/CourseSelectFormContainer.jsx, app/containers/UnitInfoContainer.jsx, app/containers/UnitSearchContainer.jsx, app/reducers/Counter.js, app/utils/Export.js, app/utils/UnitQuery.js, package.json
+ Bug fix is the incorrect handling of 'startyear' in plan.jsx. It needed to be parsed through as an integer
+ Heaps of docs + linting fixes to clean up npm test
=> [FIX][DEV] - The great 2k17 lint purge

app/components/Course/CourseStructure.jsx, app/components/TeachingPeriod/TeachingPeriod.jsx, app/components/Unit/Unit.jsx
Due to how state is currently managed, adding or moving units on top of placeholders will remove the placeholder. When you drag away or remove that unit, the placeholder should come back.
=> Implemented unit placeholders

app/components/base/Home2.jsx, app/components/modals/ClearCourseModal.jsx, app/containers/CourseSelectFormContainer2.jsx
=> just for Saurabh, 

app/components/Course/CourseEditActions.jsx, app/components/TeachingPeriod/InsertTeachingPeriodButton.jsx, app/components/base/Header.jsx, app/components/modals/LoadCourseMap.jsx, app/public/css/custom.css
- Fixed course edit actions bar to bottom of screen (for non-mobile displays)
- Add unit button now shows "Close" when sidebar is shown
=> [UI] slight improvements

app/components/Course/CourseStructure.jsx, app/components/base/Plan.jsx, app/containers/CourseSelectFormContainer.jsx, app/containers/YearFormContainer.jsx
Took redux control away from forms pending v0.3 launch so we can maintain stability
=> [FIX] Redux stability fix

app/components/TeachingPeriod/TeachingPeriod.jsx, app/components/Unit/Unit.jsx, app/components/base/Home.jsx, app/components/modals/ClearCourseModal.jsx, app/containers/CourseSelectFormContainer.jsx, app/index.jsx, app/public/css/monash.css, package.json
- Changes now display Warning Icon 
- also added warning info popup upon hover
=> [UI] Cumulative Update

app/components/Course/CourseEditActions.jsx, app/components/Course/CourseStatisticGroup.jsx, app/components/Course/CourseStructure.jsx, app/components/TeachingPeriod/InsertTeachingPeriodButton.jsx, app/components/Unit/Unit.jsx, app/components/base/Header.jsx, app/components/base/Plan.jsx, app/components/base/notify.jsx, app/components/modals/ClearCourseModal.jsx, app/components/modals/CompletedCourseModal.jsx, app/components/modals/ConfirmDeleteOverload.jsx, app/components/modals/ConfirmDeleteTeachingPeriod.jsx, app/components/modals/CustomUnitModal.jsx, app/components/modals/LoadCourseMap.jsx, app/config/routes.js, app/containers/CourseInfoButtonContainer.jsx, app/containers/UnitSearchResultsContainer.jsx, app/public/css/monash.css
- changes to course table as well as unit display
- cleaned up design
- moved view course details button
- cleaned up UI
=> [UI] Cumlative UI changes

.gitignore, .travis.yml, README.md, app/components/TeachingPeriod/TeachingPeriod.jsx, package.json, test/components/Course/CourseStatisticGroup.spec.jsx, test/components/TeachingPeriod/InsertTeachingPeriodButton.spec.jsx, test/components/TeachingPeriod/TeachingPeriod.spec.jsx, test/setup.js
Please run `npm install` to install any missing dependencies.
=> Added more test cases and added coveralls

app/actions/CourseActions.js, app/actions/DataFetchActions.js, app/components/Course/CourseStructure.jsx, app/components/Unit/Unit.jsx, app/components/modals/CustomUnitModal.jsx, app/reducers/CourseStructure.js, app/utils/ValidateCoursePlan.js
- Only bug is the inability to cancel adding units, which needs to be fixed
=> [fix] almost complete redux migration for validation

.eslintrc, app/actions/DataFetchActions.js, app/components/Course/CourseStatisticGroup.jsx, app/reducers/CourseStructure.js, test/reducers/CourseStructure.spec.js, webpack.config.js
Sometimes I wished this was more easier....
=> [C] Cumulative Updates

app/components/Unit/UnitInfoPlaceholder.jsx, app/containers/Unit/UnitInfoContainer.jsx, app/reducers/CourseStructure.js, app/utils/ValidateCoursePlan.js, test/reducers/CourseStructure.spec.js
I'm not sure about the special symbols for course codes, but it should handle course code matching and examine the correct branch accordingly.
=> parses For COURSE_CODE IN {...} and more descriptive error messages for unit info modal

app/utils/ValidateCoursePlan.js, app/utils/rules.pegjs, test/reducers/CourseStructure.spec.js
However, we need to construct the error strings better. Also, I'm not sure if it is entirely correct yet.
=> [CRE] Rules containing logical expressions "OR" and "AND" works now

app/components/Pages/Graph.jsx, app/config/routes.js, package.json
By the looks of it, d3 is the main deal for rendering force directed graphs. WebCola looks interesting as it has group hierarchies (which can used for visualising logical expressions in rules?) and constraints (so there may be a possibility to align them as a list of teaching periods).
I'll try and read more about d3 and WebCola and see how it plays out.
Please run `npm install` to install `d3` and `webcola`.
=> [UI] [CRE] [dep] add /graph for graphing units

app/components/Pages/Graph.jsx, app/containers/Unit/UnitSearchContainer.jsx, app/reducers/Index.js, app/utils/ValidateCoursePlan.js
Starting to learn more about d3 force directed graphs. Will need to research more about it and understand how to use it correctly. 
React and d3 doesn't play well with each other, as d3 mutates the node array to insert properties such as coordinates, and the nodes data comes from Redux's store, which is injected into a prop. As the nodes array is replaced by the new props in `shouldComponentUpdate`, and no coordinates data is kept, the nodes resets back to their initial positions. This is not the desired behaviour, and needs to be fixed.
Also there is no text layout such as word wrap in SVG, so I may instead insert HTML elements as foreignObjects into SVG, which will keep it's original styling as in semantic-ui-css.
=> Some more work on graphs

app/components/Pages/myFuture/CareerCardGroup.jsx, app/components/Pages/myFuture/CareerDetailContainer.jsx, app/components/Pages/myFuture/CourseCard.jsx, app/public/data/careers.json
- Updated Components
- Added new CourseCard Component renders base on props, renders card header line based off faculty
- Added CardGroup Component
- Need to fix rendering issues - cant map relatedDegrees array (possibly redux)
=> [UI][CRE][DEV] Rendering Card Engine
